### ISSUE TITLE
Broken Facets 

### ISSUE THREAD

**Issue by theberg75** [UMNLibraries/umedia#109]
### Descriptive summary

Object-level metadata fields that should be faceted are not working properly. See: https://umedia.lib.umn.edu/item/p16022coll621:222?facets%5Bcollection_name_s%5D%5B%5D=Records+of+YMCA+International+Work+in+Egypt

Check out any faceted fields: Date Created; Creator; Subjects; Parent Collection; etc. (All fields in record including collection name at bottom). This is happening for all objects across collections / contributors.

**Comment by mberkowski** [comment]
@theberg75 noticed Contributor was still not faceting. Turns out because the details view was showing `contributor` rather than `contributor_ss` where the former is fieldType `text_en` and the latter is `strings`.  Something prevents `text_en` from faceting in this context. Fixed with 70f2315
