### ISSUE TITLE
Contributor field not displaying in public view 

### ISSUE THREAD

**Issue by theberg75** [UMNLibraries/umedia#110]
**Describe the bug**
Contributor field name not displaying correctly across collections that include a Contributor in the metadata. 
**To Reproduce**
See screenshot or any of the following links. This is confirmed across all collections. 
[https://umedia.lib.umn.edu/item/p16022coll635:2](https://umedia.lib.umn.edu/item/p16022coll635:2)
[https://umedia.lib.umn.edu/item/p16022coll97:174](https://umedia.lib.umn.edu/item/p16022coll97:174)
 
![Screenshot 2023-09-07 at 1 04 19 PM](https://github.com/UMNLibraries/umedia/assets/127430672/37b5ae76-cf01-4f2c-992a-d0678dc7ce46)

**Comment by mberkowski** [comment]
Translation was missing from locales, fixed by 5e5f7d6
